default: &default


  adapter: postgresql
  encoding: unicode
  database: bookvault_api_development
  username: loisio
  password: 1234
  host: localhost
  port: 5432
  pool: 5
development:
  <<: *default
  database: bookvault_api_development

test:
  <<: *default
  database: bookvault_test
  username: loisio
  password: 1234
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: bookvault_api_production
    username: bookvault_api
    password: 1234
    host: localhost
    port: 5432
  cache:
    <<: *primary_production
    database: bookvault_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: bookvault_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: bookvault_api_production_cable
    migrations_paths: db/cable_migrate
