default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "loisio") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  database: <%= ENV.fetch("POSTGRES_DB", "bookvault_api_development") %>

development:
  <<: *default
  database: bookvault_api_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "bookvault_test") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  primary: &primary_production
    <<: *default
    database: bookvault_api_production
    username: bookvault_api
    password: <%= ENV["BOOKVAULT_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: bookvault_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: bookvault_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: bookvault_api_production_cable
    migrations_paths: db/cable_migrate
